### ISSUE TITLE
No id_token in response when getting response from auth server

### ISSUE THREAD

**Issue by michaelklopf** [maxmantz/redux-oidc#18]
Following error happens when the CallbackComponent is executing the errorCallback.
> Error: **No id_token in response**
    at t._processSigninParams (http://localhost:5004/js/bundle.js:43153:15938)
    at t.validateSigninResponse (http://localhost:5004/js/bundle.js:43153:14041)
    at http://localhost:5004/js/bundle.js:43153:4837

Here the structure I have in my application

Setting up the user Manager and adding middleware, added route for callback and home page
```
// index.js
...
import {oidc_config} from './config';
export const userManager = createUserManager(oidc_config);
const oidcMiddleware = createOidcMiddleware(userManager, () => true, false, '/callback');
...
const routes = (
  <Route path='/' component={App}>
    <IndexRedirect to="/home" />
    ....
    <Route path='/callback/:authInfo' component={CallbackPage} />
  </Route>
);

render(
  <Provider store={store}>
    <OidcProvider store={store} userManager={userManager}>
      <Router history={hashHistory}>{routes}</Router>
    </OidcProvider>
  </Provider>,
  document.getElementById('root')
);
```

Configuration for oidc
```
// config.js
export const oidc_config = {
  authority: authorizationProvider,
  client_id: client_id,
  redirect_uri: 'http://localhost:5004/#/callback/',
  response_type: 'id_token token',
  scope: 'openid profile email api',
  filterProtocolClaims: true
};
```

First component that is rendered and which renders LoginPage if no user exists
```
// HomePage.jsx
class HomePage extends Component {
  render() {
    const { user } = this.props;
    if (!user || user.expired) {
      return <LoginPage />;
    } else {
      this.context.router.push('/processes');
      return <div></div>;
    }
  }
}
```

Login simply calls signinRedirect which goes straight to the Identitiy Server 3 login form
```
// LoginPage.jsx
class LoginPage extends Component {
  constructor() {
    super();
    userManager.signinRedirect();
  }

  render() {
    return (
      <div></div>
    );
  }
}
```

Redirect from IS3 says to render this page which sets up the callbacks for the CallbackComponent. successCallback is never called because of the above mentioned error, but errorCallback is executed. I extracted the token from the location hash and set it in my application.
```
// CallbackPage.jsx
class CallbackPage extends Component {
  constructor(props, context) {
    super(props, context);
    this.successCallback = (user) => {
      //const urlBeforeRedirection = user.state.redirectUrl;
      //this.context.router.push(urlBeforeRedirection);
    };

    this.errorCallback = (error) => {
      const regex = /&access_token=(.*?)&token_type=/;
      this.props.setToken(this.props.params.authInfo.match(regex)[1], this.context.router);
    };
  }

  render() {
    return (
      <CallbackComponent
        successCallback={this.successCallback}
        errorCallback={this.errorCallback} />
    );
  }
}
```

Action sets the token in the app and routes to a specific page, application works after that and can be used, but not as intended
```
// actions.js for login
export function setToken(token, router) {
  return function(dispatch) {
    dispatch(setLoginToken(token));
    router.push('/processes');
  };
}
```

The request to the server looks like this
> Request URL:https://ouridentityserver/core/connect/authorize?client_id=theclientid&redirect_uri=http://localhost:5004/callback/&response_type=id_token%20token&scope=openid%20profile%20email%20api&state=alargevalue&nonce=anotherlargevalue
Request Method:GET
Status Code:302 Found
Remote Address:172.30.2.185:443

The response to the server looks like this
> HTTP/1.1 302 Found
Content-Length: 0
Location: http://localhost:5004/#/callback/id_token=largeIdTokenHere&access_token=largeAccessTokenHere&token_type=Bearer&expires_in=3600&scope=openid%20profile%20email%20api&state=6e36fc965faf481ca11f0ee71f2008db&session_state=largervaluehere
Server: Microsoft-IIS/7.5
X-Powered-By: ASP.NET
Date: Wed, 04 Jan 2017 09:04:25 GMT

Well, as you can see I have the problem that the successCallback is never called because there is no id_token in the response from the IS3. But instead I get the location from it with the necessary tokens.

My colleague says that the IS3 is configured correctly and he set up an example that used oidc-client-js, which works and a user object exists.

What do you think, is that a problem with the IS3 setup, or is something else working wrong here. How to your responses look from the Identity Server?

**Comment by maxmantz** [comment]
Hard to see from the config what the problem could be. I never had these issues with IS3. However one thing I've noticed: you are using react-routers hash history. This has implications on how the browser reads subsections of the URL location and can cause problems. Try to switch to browser history (without the '#' in the URL) and see if the issue still persists.

**Comment by maxmantz** [comment]
Looking closer at your redirect from IS3, I have additional belief to blame the URL hash for your issues. Take a look at the redirect from Google OpenID from my example app:
https://redux-oidc-example.herokuapp.com/callback#state=blob&access_token=blob&token_type=Bearer&expires_in=3600&id_token=very_large_blob 

As you can see, Google adds another hash to the URL. I don't know exactly how IS3 does it but your callback URL looks like this: http://localhost:5004/#/callback/id_token=blob

You see the slash behind callback? I think react-router might interpret this as a separate route (called id_token) which doesn't exist. You could also try to change the `redirect_uri` option in your oidc-client config and omit the trailing slash behind `callback`. Maybe that helps...

**Comment by michaelklopf** [comment]
Hi Maximilian,

thank you for your help. I'm trying your approach, changed everything in the front-end, but takes a little more time to handle the routes on the server side. I will come back to you with results when I'm finished. Looking forward to solve that problem, but I learned a lot about the mechanisms in the background at least.

Kind regards,

Michael

**Comment by maxmantz** [comment]
I'm always happy to help. For the sake of simplicity try changing the `redirect_uri` option in your config.js first. This would be the simplest fix possible :)

**Comment by michaelklopf** [comment]
I did, the result is looking similar to your google address now:

> https://redux-oidc-example.herokuapp.com/callback#state=blob&access_token=blob&token_type=Bearer&expires_in=3600&id_token=very_large_blob

> http://localhost:5004/callback/#id_token=idTokenHere&access_token=accessTokenHere&token_type=Bearer&expires_in=3600&scope=openid%20profile%20email%20api%20roles&state=stateThing&session_state=longThing

Slash will be gone tomorrow, when my colleague changes the AllowedRedirect entry again, because I have no database access for the system we test this on.

And I have to catch this route on the server side.
