### ISSUE TITLE
Invariant Violation: React.Children.only expected to receive a single React element child

### ISSUE THREAD

**Issue by pellea** [maxmantz/redux-oidc#26]
Hello,

I quickly checked the _beta3_ and I got this following error after a login process (with `userManager.signinRedirect`).

An unhandled exception occurred while processing the request.

```
Exception: Call to Node module failed with error: Invariant Violation: React.Children.only expected to receive a single React element child.
at invariant (...\node_modules\fbjs\lib\invariant.js:44:15)
at Object.onlyChild [as only] (...\node_modules\react\lib\onlyChild.js:33:84)
at r.value (...\node_modules\redux-oidc\dist\redux-oidc.js:1:5384)
at ...\node_modules\react-dom\lib\ReactCompositeComponent.js:796:21
at measureLifeCyclePerf (...\node_modules\react-dom\lib\ReactCompositeComponent.js:75:12)
at ReactCompositeComponentWrapper._renderValidatedComponentWithoutOwnerOrContext (...\node_modules\react-dom\lib\ReactCompositeComponent.js:795:25)
at ReactCompositeComponentWrapper._renderValidatedComponent (...\node_modules\react-dom\lib\ReactCompositeComponent.js:822:32)
at ReactCompositeComponentWrapper.performInitialMount (...\node_modules\react-dom\lib\ReactCompositeComponent.js:362:30)
at ReactCompositeComponentWrapper.mountComponent (...\node_modules\react-dom\lib\ReactCompositeComponent.js:258:21)
at Object.mountComponent (...\node_modules\react-dom\lib\ReactReconciler.js:46:35)
```

I can confirm that the _beta1_ is working properly but not the _beta3_.

**Comment by maxmantz** [comment]
You need to pass a child element into the callback component. FYI all changes between versions are referenced under [releases](https://github.com/maxmantz/redux-oidc/releases).
