### ISSUE TITLE
Fails when rendering server-side

### ISSUE THREAD

**Issue by jacek-dargiel** [maxmantz/redux-oidc#3]
We're using react's server-side rendering feature. We tried to use redux-oidc in our application, unfortunately it looks like redux-oidc does not work on the server, because it requires `sessionStorage`, which is not available in node. Is there a way to make it work with SSR?

Here's a stack trace FWIW:
```
[1] [piping] can't execute file: /path/to/project/bin/server.js
[1] [piping] error given was: ReferenceError: sessionStorage is not defined
[1]     at Function.n.get (/path/to/project/node_modules/redux-oidc/dist/redux-oidc.js:3:14695)
[1]     at new e (/path/to/project/node_modules/redux-oidc/dist/redux-oidc.js:12:28204)
[1]     at new e (/path/to/project/node_modules/redux-oidc/dist/redux-oidc.js:12:20743)
[1]     at Object.n [as createUserManager] (/path/to/project/node_modules/redux-oidc/dist/redux-oidc.js:1:1578)
[1]     at Object.<anonymous> (/path/to/project/src/utils/oauth/molManager.js:15:21)
[1]     at Module._compile (module.js:413:34)
[1]     at normalLoader (/path/to/project/node_modules/babel-core/lib/api/register/node.js:199:5)
[1]     at Object.require.extensions.(anonymous function) [as .js] (/path/to/project/node_modules/babel-core/lib/api/register/node.js:216:7)
[1]     at Module.load (module.js:357:32)
[1]     at Module._load (module.js:314:12)
```

**Comment by maxmantz** [comment]
It is possible to use your own storage interface with `oidc-client-js`. I haven't yet tried it myself, but from what I gather you can hook up pretty much anything to the `userStore` property of the `userManager` settings. See [this](https://github.com/IdentityModel/oidc-client-js/issues/32) issue for example, which talks about using `localStorage` instead of `sessionStorage`.

Your settings object should look like this:
```
const settings = {
  userStore: new WebStorageStateStore({ store: mySsrStorage }); // you would have to implement mySsrStorage on your own
  // other settings
}
``` 

[This](https://github.com/IdentityModel/oidc-client-js/blob/master/src/WebStorageStateStore.js) is the store the user manager uses when storing session data. [This](https://github.com/IdentityModel/oidc-client-js/blob/master/src/InMemoryWebStorage.js) is an example of an in-memory implementation of the `store` interface in `WebStorageStateStore` - which is what you have to build to use your SSR storage. Sadly oidc-client's wiki doesn't convey much additional information about it.

I hope this helps you. I'd be happy to hear if you could solve the issue.

**Comment by maxmantz** [comment]
Any updates on this?

**Comment by Czahoo** [comment]
Yeah, it worked, thank you very much!

**Comment by maxmantz** [comment]
Glad to hear it.
